name: Build and Test
on:
  workflow_call:
    secrets:
      SIEMENS_NPM_TOKEN:
        required: true
      SIEMENS_NPM_USER:
        required: true
      MAPTILER_KEY:
        required: true
  pull_request:

# Stops the workflow run if the PR is updated
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MAPTILER_KEY: ${{ secrets.MAPTILER_KEY }}
  MAPTILER_URL: https://api.maptiler.com/maps/voyager/style.json?key=${{ secrets.MAPTILER_KEY }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # We need this for commit-lint
      - uses: actions/setup-node@v5
        with:
          node-version: lts/jod
          cache: 'npm'
      - run: npm config set //code.siemens.com/api/v4/packages/npm/:_authToken $SIEMENS_NPM_TOKEN
        env:
          SIEMENS_NPM_TOKEN: ${{ secrets.SIEMENS_NPM_TOKEN }}
      - run: npm ci --prefer-offline --no-audit --include=optional
      - run: npm run lint:commit
      - run: npm run build:all
      - run: npm run prepare-brand
      - run: npm run build:all:update-translatable-keys # Output is needed in dist for providing default translations
      - run: git diff --exit-code "projects/**/*-translatable-keys.interface.ts"
      - run: npm run build:examples -- --define="maptilerKey='$MAPTILER_KEY'" --define="maptilerUrl='$MAPTILER_URL'"
      - run: npm run dashboards-demo:build:demo -- --progress=false
      - run: npm run dashboards-demo:build:webcomponents -- --progress=false
      - run: npm run dashboards-demo:build:mfe -- --progress=false
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test:
    runs-on: ubuntu-24.04
    # We use playwright browser to run karma tests
    container: mcr.microsoft.com/playwright:v1.55.0-noble
    env:
      # See: https://github.com/microsoft/playwright/issues/27620
      HOME: /root
    needs:
      - build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/jod
          cache: 'npm'
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - run: npm ci --prefer-offline --no-audit
      - run: npm run lint:format
      - run: npm run lint:scss
      - run: npm run lint:ng
      - run: npm run lint:playwright:eslint
      - run: npm run translate:test -- --watch=false --progress=false --code-coverage
      # - run: npm run lib:test -- --watch=false --progress=false --code-coverage
      # - run: npm run charts:test -- --watch=false --progress=false
      # - run: npm run dashboards:test -- --watch=false --progress=false
      # - run: npm run maps:test -- --watch=false --progress=false
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: dist/coverage
          retention-days: 30


  aot:
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/jod
          cache: 'npm'
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - run: npm config set //code.siemens.com/api/v4/packages/npm/:_authToken $SIEMENS_NPM_TOKEN
        env:
          SIEMENS_NPM_TOKEN: ${{ secrets.SIEMENS_NPM_TOKEN }}
      - run: npm ci --prefer-offline --no-audit --include=optional
      - run: npm run prepare-brand
      - run: npm run build:examples:aot -- --define="maptilerKey='$MAPTILER_KEY'" --define="maptilerUrl='$MAPTILER_URL'"

  documentation:
    runs-on: ubuntu-24.04
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@v5
        with:
          node-version: lts/jod
          cache: 'npm'
      - run: npm config set //code.siemens.com/api/v4/packages/npm/:_authToken $SIEMENS_NPM_TOKEN
        env:
          SIEMENS_NPM_TOKEN: ${{ secrets.SIEMENS_NPM_TOKEN }}
      - run: npm ci --prefer-offline --no-audit --include=optional
      - run: cp dist/element-examples/favicon.png docs/_src/favicon.png
      - run: uv sync
        env:
          UV_INDEX_CODE_DOCS_THEME_USERNAME: ${{ secrets.SIEMENS_NPM_USER }}
          UV_INDEX_CODE_DOCS_THEME_PASSWORD: ${{ secrets.SIEMENS_NPM_TOKEN }}
      - run: npm run docs:build:generate
        env:
          EXAMPLES_BASE: /element-examples
        if: ${{ github.ref == 'refs/heads/main' }}
      - run: npm run docs:build:api
        env:
          EXAMPLES_BASE: /element-examples
        if: ${{ github.ref != 'refs/heads/main' }}
      - run: mv dist/element-examples/ dist/design/
      - run: mv dist/dashboards-demo/ dist/design/
      - uses: actions/upload-artifact@v4
        with:
          name: pages
          path: dist/design
